export const registerArr = [
  {
    id: "fullname",
    name: "name",
    type: "text",
    text: "name",
    label: "Full Name",
    classbody: "textbody",
    classname: "textclass",
    classitem: "textitem",
  },
  {
    id: "email",
    name: "email",
    type: "email",
    text: "email",
    label: "Email",
    classbody: "textbody",
    classname: "textclass",
    classitem: "textitem",
  },
  {
    select: "select",
    label: "Phone Network",
    name: "network",
    id: "network",
    valueArray: [{ value: "MTN" }, { value: "AIRTEL" }, { value: "GLO" }],
  },
  {
    id: "phone",
    label: "Phone",
    name: "phone",
    type: "text",
    text: "phone",
    classbody: "phonemainbody",
  },
  {
    submit: "Proceed",
    classbody: "submitbody",
    classname: "submitclass",
    classitem: "submititem",
  },
];
