export const registerArr = [
  {
    id: "fullname",
    name: "name",
    type: "text",
    text: "name",
    label: "Full Name",
    classbody: "textbody",
    classname: "textclass",
    classitem: "textitem",
  },
  {
    id: "email",
    name: "email",
    type: "email",
    text: "email",
    label: "Email",
    classbody: "textbody",
    classname: "textclass",
    classitem: "textitem",
  },
  {
    id: "phone",
    label: "Phone",
    name: "phone",
    type: "text",
    text: "name",
    classbody: "textbody",
    classname: "textclass",
    classitem: "textitem",
  },
  {
    submit: "Proceed",
    classbody: "submitbody",
    classname: "submitclass",
    classitem: "submititem",
  },
];
